/* Generated by Yosys 0.57+30 (git sha1 23e4c0e42, g++ 14.2.1 -fPIC -O3) */

(* top =  1  *)
(* src = "ShiftReg4bit.v:2.1-17.10" *)
module shift_reg_4bit(clk, rst, din, q);
  (* src = "ShiftReg4bit.v:3.23-3.26" *)
  input clk;
  wire clk;
  (* src = "ShiftReg4bit.v:4.23-4.26" *)
  input rst;
  wire rst;
  (* src = "ShiftReg4bit.v:5.23-5.26" *)
  input din;
  wire din;
  (* src = "ShiftReg4bit.v:6.23-6.24" *)
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "ShiftReg4bit.v:5.23-5.26" *)
  wire _04_;
  wire _05_;
  (* src = "ShiftReg4bit.v:6.23-6.24" *)
  wire _06_;
  (* src = "ShiftReg4bit.v:6.23-6.24" *)
  wire _07_;
  (* src = "ShiftReg4bit.v:6.23-6.24" *)
  wire _08_;
  (* src = "ShiftReg4bit.v:4.23-4.26" *)
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  AND2X1 _14_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_)
  );
  AND2X1 _15_ (
    .A(_05_),
    .B(_07_),
    .Y(_02_)
  );
  AND2X1 _16_ (
    .A(_05_),
    .B(_08_),
    .Y(_03_)
  );
  INVX1 _17_ (
    .A(_09_),
    .Y(_05_)
  );
  AND2X1 _18_ (
    .A(_04_),
    .B(_05_),
    .Y(_00_)
  );
  (* src = "ShiftReg4bit.v:9.5-15.8" *)
  DFFPOSX1 _19_ (
    .CLK(clk),
    .D(_10_),
    .Q(q[0])
  );
  (* src = "ShiftReg4bit.v:9.5-15.8" *)
  DFFPOSX1 _20_ (
    .CLK(clk),
    .D(_11_),
    .Q(q[1])
  );
  (* src = "ShiftReg4bit.v:9.5-15.8" *)
  DFFPOSX1 _21_ (
    .CLK(clk),
    .D(_12_),
    .Q(q[2])
  );
  (* src = "ShiftReg4bit.v:9.5-15.8" *)
  DFFPOSX1 _22_ (
    .CLK(clk),
    .D(_13_),
    .Q(q[3])
  );
  assign _04_ = din;
  assign _09_ = rst;
  assign _10_ = _00_;
  assign _06_ = q[0];
  assign _11_ = _01_;
  assign _07_ = q[1];
  assign _12_ = _02_;
  assign _08_ = q[2];
  assign _13_ = _03_;
endmodule
